import httplib


# Re-use http status codes as Cielo error codes
class EID:
    CONTINUE = httplib.CONTINUE
    SWITCHING_PROTOCOLS = httplib.SWITCHING_PROTOCOLS
    PROCESSING = httplib.PROCESSING
    OK = httplib.OK
    CREATED = httplib.CREATED
    ACCEPTED = httplib.ACCEPTED
    NON_AUTHORITATIVE_INFORMATION = httplib.NON_AUTHORITATIVE_INFORMATION
    NO_CONTENT = httplib.NO_CONTENT
    RESET_CONTENT = httplib.RESET_CONTENT
    PARTIAL_CONTENT = httplib.PARTIAL_CONTENT
    MULTI_STATUS = httplib.MULTI_STATUS
    IM_USED = httplib.IM_USED
    MULTIPLE_CHOICES = httplib.MULTIPLE_CHOICES
    MOVED_PERMANENTLY = httplib.MOVED_PERMANENTLY
    FOUND = httplib.FOUND
    SEE_OTHER = httplib.SEE_OTHER
    NOT_MODIFIED = httplib.NOT_MODIFIED
    USE_PROXY = httplib.USE_PROXY
    TEMPORARY_REDIRECT = httplib.TEMPORARY_REDIRECT
    BAD_REQUEST = httplib.BAD_REQUEST
    UNAUTHORIZED = httplib.UNAUTHORIZED
    PAYMENT_REQUIRED = httplib.PAYMENT_REQUIRED
    FORBIDDEN = httplib.FORBIDDEN
    NOT_FOUND = httplib.NOT_FOUND
    METHOD_NOT_ALLOWED = httplib.METHOD_NOT_ALLOWED
    NOT_ACCEPTABLE = httplib.NOT_ACCEPTABLE
    PROXY_AUTHENTICATION_REQUIRED = httplib.PROXY_AUTHENTICATION_REQUIRED
    REQUEST_TIMEOUT = httplib.REQUEST_TIMEOUT
    CONFLICT = httplib.CONFLICT
    GONE = httplib.GONE
    LENGTH_REQUIRED = httplib.LENGTH_REQUIRED
    PRECONDITION_FAILED = httplib.PRECONDITION_FAILED
    REQUEST_ENTITY_TOO_LARGE = httplib.REQUEST_ENTITY_TOO_LARGE
    REQUEST_URI_TOO_LONG = httplib.REQUEST_URI_TOO_LONG
    UNSUPPORTED_MEDIA_TYPE = httplib.UNSUPPORTED_MEDIA_TYPE
    REQUESTED_RANGE_NOT_SATISFIABLE = httplib.REQUESTED_RANGE_NOT_SATISFIABLE
    EXPECTATION_FAILED = httplib.EXPECTATION_FAILED
    UNPROCESSABLE_ENTITY = httplib.UNPROCESSABLE_ENTITY
    LOCKED = httplib.LOCKED
    FAILED_DEPENDENCY = httplib.FAILED_DEPENDENCY
    UPGRADE_REQUIRED = httplib.UPGRADE_REQUIRED
    INTERNAL_SERVER_ERROR = httplib.INTERNAL_SERVER_ERROR
    NOT_IMPLEMENTED = httplib.NOT_IMPLEMENTED
    BAD_GATEWAY = httplib.BAD_GATEWAY
    SERVICE_UNAVAILABLE = httplib.SERVICE_UNAVAILABLE
    GATEWAY_TIMEOUT = httplib.GATEWAY_TIMEOUT
    HTTP_VERSION_NOT_SUPPORTED = httplib.HTTP_VERSION_NOT_SUPPORTED
    INSUFFICIENT_STORAGE = httplib.INSUFFICIENT_STORAGE
    NOT_EXTENDED = httplib.NOT_EXTENDED

    def __init__(self):
        super(EID, self).__init__()